language: go

go:
  - 1.3
  - 1.4
  - tip

script: 
 - go test -cpu=1,2,4 ./na64
 - go test -cpu=4 -race ./na64
 - go test -cpu=1,2,4 ./na32
 - go test -cpu=4 -race ./na32
 - go run genarray.go -compare
 - chmod ugo+x testfmt.sh
 - ./testfmt.sh
